# Generated by Django 4.0.4 on 2022-05-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='categoryname', max_length=50)),
                ('cat_img', models.ImageField(upload_to='cat_img')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(default='null', max_length=100)),
                ('ing_type', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='requestrecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrec_name', models.CharField(default='Name of recipe', max_length=100)),
                ('rrec_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NVEG', 'Non Vegetarian'), ('VEGAN', 'Vegan')], default='NVEG', max_length=5)),
                ('cat_name', models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('rec_type', models.CharField(default='null', max_length=10)),
                ('prep_time', models.SmallIntegerField(default=5)),
                ('serve_people', models.SmallIntegerField(default=2)),
                ('meal', models.CharField(default='allmeals', max_length=50)),
                ('img', models.ImageField(upload_to='recipe_imgs')),
                ('cat_name', models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('rec_type', models.CharField(default='null', max_length=10)),
                ('prep_time', models.SmallIntegerField(default=5)),
                ('serve_people', models.SmallIntegerField(default=2)),
                ('meal', models.CharField(default='allmeals', max_length=50)),
                ('rec_desc', models.CharField(default='null', max_length=300)),
                ('img', models.ImageField(upload_to='recipe_imgs')),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails')),
            ],
        ),
    ]
