# Generated by Django 4.0.4 on 2022-05-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_info',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails'),
        ),
        migrations.AlterField(
            model_name='requestrecipe',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails'),
        ),
    ]
