# Generated by Django 4.0.4 on 2022-05-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_alter_recipe_info_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrecipe',
            name='rrec_name',
            field=models.CharField(max_length=100),
        ),
    ]
