# Generated by Django 4.0.4 on 2022-05-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0003_ingredients_ing_type_recipe_detail_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
