# Generated by Django 4.0.4 on 2022-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0004_alter_recipe_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
