# Generated by Django 4.0.4 on 2022-05-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0004_alter_requestrecipe_rrec_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_detail',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaapp.catdetails'),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaapp.catdetails'),
        ),
        migrations.AlterField(
            model_name='requestrecipe',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaapp.catdetails'),
        ),
    ]
