# Generated by Django 4.0.4 on 2022-05-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0005_alter_recipe_detail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('rec_type', models.CharField(default='null', max_length=10)),
                ('prep_time', models.SmallIntegerField(default=5)),
                ('serve_people', models.SmallIntegerField(default=2)),
                ('meal', models.CharField(default='allmeals', max_length=50)),
                ('rec_desc', models.CharField(default='null', max_length=300)),
                ('img', models.ImageField(upload_to='recipe_imgs')),
                ('cat_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails')),
            ],
        ),
    ]
