# Generated by Django 4.0.4 on 2022-05-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0005_alter_recipe_detail_cat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_info',
            name='meal',
        ),
        migrations.AlterField(
            model_name='catdetails',
            name='cat_img',
            field=models.ImageField(upload_to='static/cat_img'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing_type',
            field=models.CharField(choices=[('Vegetable & Green', 'Vegetable & Green'), ('Fruits & Berries', 'Fruits & Berries'), ('Baking', 'Baking'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Herbs & Spices', 'Herbs & Spices')], default='Vegetable & Green', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='cat_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails'),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='prep_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='rec_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe_info',
            name='serve_people',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Recipe_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField()),
                ('step_desc', models.CharField(max_length=200)),
                ('qty', models.IntegerField(null=True)),
                ('ingr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.ingredients')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.recipe_info')),
            ],
        ),
    ]
