# Generated by Django 4.0.4 on 2022-05-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0008_alter_ingredients_ing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_detail',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.catdetails'),
        ),
    ]
