# Generated by Django 4.0.4 on 2022-05-21 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaapp', '0011_getingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='getingredients',
            name='ing_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='instaapp.ingredients'),
        ),
        migrations.AlterField(
            model_name='getingredients',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
